### ISSUE TITLE
Oh nice plugin I am in love already, one more feature requst if possible

### ISSUE THREAD

**Issue by ahmadie** [dosimple/workspace.vim#2]
OK I know where are you coming from i3 background and this plugin work exactly similar to i3 workspaces idea, which is totallly perfect and I hope you do not change any of existing commands or logic already perfect on spot 100% !!!

I would like you to add one more feature which also i3 related to make this plugin perfect !!! A command to move an existing/current buffer to another workspace !! The command would look like "move container to workspace n" of i3.

Might be "move buffer to"
:MBT n

Please I hope to hear from you !

**Comment by ahmadie** [comment]
I found WS_B_Move so I created binding and create pull req, please approve !

**Comment by ahmadie** [comment]
I have added the following feature in my fork, feel free to move it here:
-Opening an existing buffer switch to that tab/buffer.
-Now can move tab between working spaces.
-C-^ move to that tab/buffer

**Comment by dosimple** [comment]
@ahmadie, thank you for reporting the issue. For the sake of consistency, command name WSbmv has been added. For the pull request, we could continue the conversation there.
