### ISSUE TITLE
WSbmv will exchange between 2 buffers sometime

### ISSUE THREAD

**Issue by ahmadie** [dosimple/workspace.vim#6]
with only 2 files WSbmv does not work as expected

1- Open new nvim session
2- :e file1.txt
2- :e file2.txt
3- :WSbmv 2
4- :WS 1
5- :WSbmv 2

I moved both file1.txt & file2.txt to WS 2, but this will result in file1.txt in WS 1

**Comment by dosimple** [comment]
Ok, this is a bug. The handling of alternate buffer is currently somewhat neglected - that is the root of the issue. Thanks for reporting, I will look into it.
