### ISSUE TITLE
Existing buffers moves between workspaces on :e or c-^

### ISSUE THREAD

**Issue by ahmadie** [dosimple/workspace.vim#7]
I am not sure if this functionality should be part of this plugin,

:e file1.txt
:WSbmv 2
:WS 1
:e file1.txt

I would expect to jump to WS2 and view file1.txt, but what happens is that file1.txt moves to WS1. The same problem happens when using c-^ (marks etc) to switch back to prev buffer will bring that buffer to current workspace.

**Comment by dosimple** [comment]
Apart from "c-^ (marks etc)" handling behaviour, the behaviour produced by `:e ..`, `:WSbmv`, etc is the expected one, requested by #3.

And yes, the handling of alternate buffer (I'm looking into it) and jumping with marks needs more work.

**Comment by dosimple** [comment]
Alternate buffer handling has been improved now. So behaviour of `c-^` is fixed.
